### ISSUE TITLE
Raise f-I curve

### ISSUE THREAD

**Issue by jrieke** [jrieke/drosophila-dynamics#1]
@borismarin @pgleeson @cengique I created a fork of the drosophila model here to work on the model dynamics and investigation for my bachelor thesis. Will start with some of the points in the [Google doc](https://docs.google.com/document/d/1qVtktxFz98A3FiX_MJRh9t_ozOAvjytDWjKCwDBWHIk/edit?usp=sharing) @borismarin and I created.

@cengique if you have any ideas what could be interesting to explore, feel free to add them in the doc or open an issue in this repo

**Comment by jrieke** [comment]
I used the NeuroML2 version of the isopotential model for this. Quick plot of the results is [here](https://plot.ly/~j_rieke/15/firing-rate-hz-vs-i-pulse-pa/), data is [here](https://github.com/jrieke/drosophila-dynamics/tree/master/f-I-curve). Shape and frequency values are in accordance with fig. 2B from the paper:

![image](https://cloud.githubusercontent.com/assets/5103165/10229083/982b03dc-6876-11e5-9aca-c73afff9db92.png)

@cengique Are the current values in the figure above relative to the holding current of -12 pA (so that it corresponds to 0 pA on the horizontal axis)?

**Comment by borismarin** [comment]
@jrieke could you do it backwards, i.e., start from an I value for which you have periodic firing, then decrease I; you should use the "final condition" (i.e. the last point in the timeseries for a given I_i value) as the initial condition when integrating for the next I_j < I_i
While the simulation runs, think about what you expect to see...

**Comment by borismarin** [comment]
Some other interesting explorations:
- try fitting a power law to the data. Again, while least-squares works, think about what you expect to get...
- what happens if you add noise to the system? footnote: read about numerical integration of SDE ([Kloeden/Platen](http://www.springer.com/us/book/9783540540625)) and [noisy HH](http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1002247)

**Comment by cengique** [comment]
@jrieke: Yes, this includes the -12 pA bias current, which is similar to current used in experiments to keep the neuron at rest at -60 mV.
By the way, I have two high school students who are interning with me this semester, and I was wondering if you can guide us on how to use your new NeuroML model for them to play around. Can you recommend a simple simulator that this would easily work with? What are you using for instance?
Also, if you're asking me what's important to do with this model, I'd say to add the calcium and calcium-dependent potassium channels into it. This will require some data fitting, but we have partial data and a lot of fitting procedures in Matlab (part of Pandora). Let me know if you're interested in contributing to this endeavor. Should I open an issue about this?

**Comment by borismarin** [comment]
@cengique  have a look at the new simulation capabilities of [geppetto](http://live.geppetto.org), which now underlies OSB. Ideally (usability isn't perfect yet, some initial configuration might be needed), users should be able to run NeuroML/Lems simulations straight from the browser, without having to install any simulator.
That being said, NeuroML models can be exported to a variety of formats (neuron, genesis, brian, nest, even matlab, c, xpp or run natively for simple models like isopotential.ode) using [jNeuroML](https://github.com/NeuroML/jNeuroML).

**Comment by cengique** [comment]
@borismarin geppetto looks really cool and it's at a good level for my students. So in OSB I can already browse my model and see the isopotential model and the morphology, but in geppetto the _experiments_ section looks empty. How do I define an experiment and maybe show a voltage trace or something?

**Comment by jrieke** [comment]
@borismarin Is it already possible to do this without generating a Geppetto simulation file? If so, how?

@cengique For a simple simulation, you can also just run `jnml run.xml` in the isopotential_NeuroML2 folder.

**Comment by jrieke** [comment]
@cengique Does it look like below? If so, you can simply double click on one of the squares on the left to open the simulation. For custom simulations (including the Drosophila model), I do not really know how that works in Geppetto at the moment.

![image](https://cloud.githubusercontent.com/assets/5103165/10235208/b62c11fe-689a-11e5-90d7-c17f26fe485c.png)

**Comment by cengique** [comment]
@jrieke yes, I was able to browse and see the existing models in geppetto, but I wanted the students to simulate my model because we want to do some additional work on it.
Thanks for the `jnml` example, I will try it!

**Comment by jrieke** [comment]
@cengique To answer on your original questions, sure, I am happy to show them around - feel free to open issues, or write me via email (johannes.rieke@gmail.com), or we can also set up a Google Hangout if your students need some guidance on this. What do you want to do with your students? Anything that might be interesting for me?
Also, it would be great if you could open an issue on the Calcium channels (probably rather in your repo, because it's an addition to the model that could be used beyond the scope of my thesis) - I can't promise that I will get around to it, though.

**Comment by jrieke** [comment]
Plot with increasing and decreasing current steps:

![plot](https://cloud.githubusercontent.com/assets/5103165/10265608/aee37632-6a37-11e5-8c0a-b4f2db20798d.png)

**EDIT**: Slight mistake here, the rheobase values have to be 9.27 pA and 10.10 pA (in relation to the -12 pA holdig current), of course.

The frequencies are equal, the only difference is that with decreasing current steps the neuron continues to spike down to -2.73 pA (tonic-silence rheobase) instead of -1.90 pA (silence-tonic rheobase). @borismarin I guess this means that the system has two stable solutions between these points and one stable solution above. I think [this paper](http://www.sciencedirect.com/science/article/pii/0025556480901091) should contain something in that direction, will read it.

**Comment by jrieke** [comment]
@cengique I created an issue about Geppetto in your repo (see above) and asked Matteo, the main developer behind Geppetto, for help.

One more footnote: As some of the data files were too big for git, I put them in a [Google Drive folder](https://googledrive.com/host/0B2xSDxvcBl6KLWVTd0lLZ2E5Rmc/) and created a short script in this repo (`getdata.py`) that downloads these files and sorts them into the respective directories.

**Comment by borismarin** [comment]
Yep, @jrieke. You've found hysteresis. And that's not unexpected. It won't
hurt reading Rinzel's paper, but I guess it's about time we have a hangout
and start thinking in terms of dynamical systems - enough brute-force!
That will allow you to predict things like this difference in rheobase,
without performing any simulations (or did you think I had scripts to run
all those simulations but kept them hidden from you ;) ?)

**Comment by borismarin** [comment]
Wrt to geppetto, first thing that needs to be done is replacing `file` with
`href` in all `Include` statements, which I have done in my fork. Then,
geppetto will be able to persist this model properly. After that, there is
a bunch of console-based commands to define what will be recorded and which
simulator to be used - all very undocumented, but I have already asked
Matteo and Adrian to give us a hand. I will have a go with on Tuesday.

**Comment by borismarin** [comment]
@jrieke @cengique shall we keep this discussion "clean", i.e. move posts unrelated to the issue at hand ("f-I curve"),  to the relevant issues? I sometimes find it annoying having to skim through a lot of noise when trying to find specific answers for a given github issue. (Not forgetting that I am responsible for much of the noise in this one myself...)

**Comment by jrieke** [comment]
@borismarin Let's just put any further discussion about Geppetto in the issue I created for it

**Comment by cengique** [comment]
@borismarin : understood, sorry to go offtopic! :)
@jrieke : I'll send you an email about my students and also create an issue in my repo about the Ca channels. Cheers.

**Comment by jrieke** [comment]
TODO: Look at variation of frequencies

**Comment by borismarin** [comment]
@jrieke may I delete my off-topic posts from this thread then?

**Comment by jrieke** [comment]
@borismarin Feel free to delete anything that is off-topic or move it to the new issue if  it could still be of use.

**Comment by pgleeson** [comment]
@jrieke note the method in pyNeuroML: generate_current_vs_frequency_curve() https://github.com/NeuroML/pyNeuroML/blob/master/examples/generate_if_curve.py.

pyNeuroML could be useful for running multiple simulations & analysisng the results.

Also don't forget pyelectro ([my fork](https://github.com/pgleeson/pyelectro)) for extracting maxima, friring properties etc: https://github.com/pgleeson/pyelectro/blob/master/test/test_analysis.py#L75

**Comment by jrieke** [comment]
@pgleeson Wow, those scripts look really cool! I had to add a parameter to generate_current_vs_frequency_curve to account for a different spike threshold than the default 0 mV - I just sent you a pull request with the change. 
I don't have so much time during the next days (and I already have most data for the isopotential model now), but I will definitely look into all the analysis functions (might be handy for looking at the two-compartment model).
