### ISSUE TITLE
Make some plots of trajectories in phase space

### ISSUE THREAD

**Issue by jrieke** [jrieke/drosophila-dynamics#10]
For example V against mKf, like this:
![image](https://cloud.githubusercontent.com/assets/5103165/11080970/36bea302-8819-11e5-8f85-a29f83c5d749.png)

Possibly add locations of equilibria and min/max values of limit cycles from bifurcation diagram.

**Comment by jrieke** [comment]
![phase_space](https://cloud.githubusercontent.com/assets/5103165/11105660/a5ac13aa-88d0-11e5-9d17-54d459a517c5.png)

A-D as in #7 (in fact, those are the very same simulation runs).
Black circles are stable equilibria, white circles are instable equlibria and vertical lines are min/max values of the limit cycle (values for these points taken from the bifurcation diagram).

**Comment by borismarin** [comment]
Again, the fact that you have another stable equilibrium (before/after
switching on/off the bias, not shown as a black dot) deserves explanation.

**Comment by jrieke** [comment]
Included a red dot for the rest state and will explain this in the text. 
Also, I thought about making a closeup of the lower left region of B (as an extra figure), and put in some arrows that show how the short current pulses push the trajectory from the equilibrium across the separatrix towards the limit cycle and back.

![phase_space](https://cloud.githubusercontent.com/assets/5103165/11126532/a89ea254-896f-11e5-8301-beb76a9d9e77.png)

**Comment by borismarin** [comment]
*unstable, not instable
*rest state IS a stable equilibrium (albeit for a different parameter value)
*separatrix <-> saddle stable manifold

**Comment by jrieke** [comment]
![image](https://cloud.githubusercontent.com/assets/5103165/11133686/a088f376-8997-11e5-8ee4-c842255bfde6.png)
Better?
