### ISSUE TITLE
Find rheobase

### ISSUE THREAD

**Issue by jrieke** [jrieke/drosophila-dynamics#2]
caveats: find it for the silence-tonic and for the tonic-silence transitions; think about spike delays

**Comment by jrieke** [comment]
silence -> tonic: (-1.90 +- 0.01) pA
tonic -> silence: (-2.73 +- 0.01) pA

See plot and discussion in #1 
Created separate issue for spike delays ( #3 )

**Comment by borismarin** [comment]
Now that you have the infrastructure in place, it would also be interesting to further play with the system near these transitions. How does spiking appear/disappear? Are there transient spikes close to the transition? Is there a significant delay (related to #3)? Are there changes in spike shape/amplitude? Apply sharp, short square current pulses (crude approximation to deltas for the physicist in you) to the system. When is it excitable (like "real" neurones)?

**Comment by jrieke** [comment]
Oh yeah, I forgot to mention that: The neuron always goes right into tonic spiking, there are no single action potentials around the rheobase (also checked this for a few values between -1.90 pA and -1.91 pA with long simulation times). 
Just looked at spike shapes: There are no visible differences between the current steps in terms of shape. The amplitude of the spikes changes a bit - opened #4 to investigate this. Also, the first spike is always a bit larger than the other ones (this difference is minimal around the rheobase, becomes visible for >0 pA and is very significant for large currents).

**Comment by borismarin** [comment]
How are you choosing the initial conditions? Should it make a difference?

**Comment by borismarin** [comment]
Can in induce firing via a a short (delta-like) I pulse when silence and tonic spk coexist?

**Comment by jrieke** [comment]
See readme [here](https://github.com/jrieke/drosophila-dynamics/tree/master/rheobase). I always let the system settle for 5000 ms, so I think ~~the initial conditions (or rather, the conditions of the current steps before) shouldn't make a difference~~ (EDIT: see below). I also looked at the silence -> tonic transition by going from resting state (I=-12 pA) right to a single current step, and the rheobase occured at an amplitude of -1.90 pA as well.

For the delta pulses, see #5

**Comment by jrieke** [comment]
To correct on this: For the tonic -> silence transition, the rheobase does of course depend on the previous conditions (for example, starting with tonic spiking at a 30 pA current step, the transition to silence occurs at -2.60 pA). The rheobase reported above (-2.73 pA) was the smallest rheobase current I could get (by approaching it in 0.01 pA steps).
