### ISSUE TITLE
Replicate delays to first spike

### ISSUE THREAD

**Issue by jrieke** [jrieke/drosophila-dynamics#3]

**Comment by jrieke** [comment]
![delay_to_first_spike](https://cloud.githubusercontent.com/assets/5103165/10268580/a7bb371a-6abd-11e5-8778-843a38516d03.png)

At the rheobase (Ipulse = -1.90 pA or - in relation to the -12 pA holding current - at 10.10 pA) the delay to first spike becomes ~2700 ms (not shown here; can be tuned to even longer delays with a more detailed value for the rheobase).

**Comment by cengique** [comment]
@jrieke @borismarin : Analyzing delays in this model a bit more can be rewarding. There's an argument in the literature that Kf (Shal) channels are singlehandedly responsible for creating delays in these neurons (cf. papers by Carsten Duch et al), but as you can see in this model, we can get delays (almost) without Kf. I think a paper can be written to show to experimentalists that Kf is not the only mechanism to generate delays and also explain why the experiments may be reaching the wrong conclusion. If you guys can really pinpoint the dynamical mechanism resulting in delays, we can make a strong argument. Let me know if you're interested to explore in this direction.

**Comment by borismarin** [comment]
@cengique that's something I expect  @jrieke to address systematically
after this round of brute force exploration. The mechanism for the delay is
clear in this model; the three of us could have a chat about it when
@jrieke comes to London (end of Oct).

**Comment by cengique** [comment]
Sounds good @borismarin ! I'd be happy to put together the literature support for my argument. Please remind me when it's closet to when you guys get together.

**Comment by jrieke** [comment]
@cengique Sounds very interesting - I will put it into the list of ideas in our Google doc. Looking forward to discuss this!
