### ISSUE TITLE
Investigate excitability in reaction to short square current pulses

### ISSUE THREAD

**Issue by jrieke** [jrieke/drosophila-dynamics#5]
Especially look at region between the two rheobases ( #2 ) where silence and tonic spiking coexist

**Comment by jrieke** [comment]
Between the two rheobase values (-2.73 pA < I_const < -1.90 pA, where I_const is the amplitude of the constant current step), the system starts to spike tonically after a short current pulse (50 pA, 10 ms - I also tried stronger pulses but they did not change the situation). For I_const <= -2.73 pA, a short current pulse only causes one or two successive spikes, but then the system goes back to rest.

I guess this means that the stable limit cycle already exists once I_const > -2.73 pA (in accordance with the behaviour for decreasing current steps in #1 ), and  the limit cycle and the stable equilibrium coexist for -2.73 pA < I_const < -1.90 pA (with the short current pulse pushing the system from equilibrium to the limit cycle).

**Comment by borismarin** [comment]
Way to go, Johannes. Now, what are the bifurcations responsible for each
transition? Remember to consider spike amplitudes, frequency at the onset
of oscillations, presence of damped oscillations towards the eq...

**Comment by jrieke** [comment]
I think it shuld be a saddle-homoclinic orbit bifurcation at the tonice-silence transition (-2.73 pA) and a saddle-node (off limit cycle) bifurcation at the silence-tonic transition (-1.90 pA). 

(Shortly: Bistability and type II excitability rule out saddle-node on invariant circle; bistability, missing subthreshold oscillations and type II spiking rule out supercritical Hopf; missing subthreshold oscillations rule out subcritical Hopf. I do not completely understand spike amplitudes for all possible bifurcations yet, but we can discuss it in London)

**Comment by borismarin** [comment]
That was also my diagnosis. You are ready to do it numerically now, and
then start relating this scenario to properties like delay to 1st spk.
