### ISSUE TITLE
Should this fork go on a branch rather than being on master?

### ISSUE THREAD

**Issue by cengique** [jrieke/drosophila-dynamics#6]
@jrieke : are you planning to eventually merge all you do here to my repo? If not, maybe you should go on your own branch so that you can still keep the `master` here in sync with my repo and we can share commits if we need to. Do you think this is good git workflow? If you think there's no benefit to it, I don't have a problem if you want to stay on `master`.

**Comment by jrieke** [comment]
@cengique No, I think it would be too much overhead for your repo (but maybe we can include a link to this repo in your README there once I'm done). I am currently thinking of excluding the model from this repo anyway, as the small back-and-forth changes I am doing to get the data don't really make sense to be in version control. Let me see what I will add to this repo during the next weeks, then I'll decide..

**Comment by jrieke** [comment]
Decided to exclude the model from this repo and detach the fork as there will not be much development of the model in this repo.
