### ISSUE TITLE
Find power laws for plots

### ISSUE THREAD

**Issue by jrieke** [jrieke/drosophila-dynamics#8]

**Comment by jrieke** [comment]
@borismarin You said that certain power laws indicate certain bifurcations - do you have any literature on that?

**Comment by borismarin** [comment]
Strogatz table 7.4.1 p 264

**Comment by jrieke** [comment]
See red curves in plots below. Only fitted a small region near the bifurcations (in accordance with Strogatz). Made both curves go through zero at the values of the bifurcations (-2.73 pA and 59.70 pA).

f-I-curve (inverse logarithmic fit near the homoclinic bifurcation; form of the equation is taken from Izhikevich book, fig. 6.30 on p. 189):

![f-i-curve](https://cloud.githubusercontent.com/assets/5103165/11911101/0c3a114c-a60b-11e5-88df-4daf86eaed9b.png)

Amplitudes (square root fit near the supercritical Hopf): 

![amplitudes](https://cloud.githubusercontent.com/assets/5103165/11911103/10452a6a-a60b-11e5-9493-79d2083ac8ff.png)

**Comment by borismarin** [comment]
Lovely. Maybe it will be clearer if you factor out par-par\* where par\* is
the parameter value for the bifurcations.

**Comment by borismarin** [comment]
BTW, do you say "mean firing rate" because firing is irregular or because
you are not disregarding transients?

**Comment by borismarin** [comment]
I'd also have an inset for the f-I plot zooming around 0 pA

**Comment by jrieke** [comment]
par*: Great idea, will do that!
mean: It's pretty regular, but I am averaging about a few spikes anyway (disregarding the first and last few spikes of each current step). Will include a sentence saying that spiking is regular. Also want to polish the legend/label descriptions after I'm done with the important stuff. 
inset: I had the same idea, will look into it after I've finished everything else.
